name: build docker images

on:
  push:
    branches:
      - main
    paths:
      - Golang/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: get latest sha of 8 digits.
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse HEAD | cut -c 33-40)" >> $GITHUB_ENV

      - name: Build image
        run: |
          for file in Golang/*; do
          #docker build $file/.
          docker build -t ghcr.io/rajeshroyal/test-5/golang:alpine-${{ env.GITHUB_SHA_SHORT }} $file/.
          docker build -t ghcr.io/rajeshroyal/test-5/golang:alpine-latest $file/.
          done

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: Rajesh-enlume
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Github Container Registry
        run: |
          docker push ghcr.io/rajeshroyal/test-5/golang:alpine-${{ env.GITHUB_SHA_SHORT }}
          docker push ghcr.io/rajeshroyal/test-5/golang:alpine-latest
          
