name: build docker images

on:
  push:
    branches:
      - main
    paths:
      - golang/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: get latest sha of 8 digits.
        run: echo "GITHUB_SHA_SHORT=$(git rev-parse HEAD | cut -c 33-40)" >> $GITHUB_ENV

      - name: build image
        run: |
          for file in golang/*; do
          
          docker build -t ghcr.io/royalrajesh/test-5/golang-alpine:${{ env.GITHUB_SHA_SHORT }} $file/.
          docker tag alpine:${{ env.GITHUB_SHA_SHORT }} ghcr.io/royalrajesh/test-5/golang-alpine:latest
          docker build -t ghcr.io/test-5/dockerfiles3/golang-alpinefuzz:${{ env.GITHUB_SHA_SHORT }} $file/.
          docker tag alpinefuzz:${{ env.GITHUB_SHA_SHORT }} ghcr.io/royalrajesh/test-5/golang-alpinefuzz:latest
          done

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: royalrajesh
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Github Container Registry
        run: |
          
          
          docker push -a ghcr.io/royalrajesh/test-5/golang
          
          
